# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SecQuery
                                 A QGIS plugin
 This plugin is used to render a circle with 16 wind-rose sectors and query 
 the data in them.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-31
        copyright            : (C) 2022 by Srividya Subramanian
        email                : srividya.ssa@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SecQuery class from file SecQuery.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .secquery import SecQuery
    return SecQuery(iface)
